#!/bin/bash
# TDD Scaffold Generator
# Creates test file structure based on PES module definitions
#
# Usage: ./tdd-scaffold.sh <module-name> [test-framework]
# Example: ./tdd-scaffold.sh order-service jest

MODULE=$1
FRAMEWORK=${2:-jest}

if [ -z "$MODULE" ]; then
  echo "Usage: ./tdd-scaffold.sh <module-name> [test-framework]"
  exit 1
fi

echo "Creating TDD scaffold for: $MODULE"
echo "Test framework: $FRAMEWORK"

mkdir -p "src/$MODULE"
mkdir -p "tests/unit/$MODULE"
mkdir -p "tests/integration/$MODULE"

cat > "tests/unit/$MODULE/$MODULE.test.js" << TESTEOF
/**
 * Unit tests for $MODULE
 * Generated by TDD Scaffold — fill in based on PES
 *
 * TDD Cycle:
 * 1. Write a failing test (Red)
 * 2. Write minimum code to pass (Green)
 * 3. Refactor without changing behavior
 */

describe('$MODULE', () => {
  describe('Happy Path', () => {
    test.todo('should [first AC from PRD]');
    test.todo('should [second AC from PRD]');
  });

  describe('Edge Cases', () => {
    test.todo('should handle [edge case from PRD]');
  });

  describe('Error Handling', () => {
    test.todo('should gracefully handle [failure scenario]');
  });
});
TESTEOF

echo "✅ Scaffold created:"
echo "   src/$MODULE/"
echo "   tests/unit/$MODULE/$MODULE.test.js"
echo "   tests/integration/$MODULE/"
echo ""
echo "Next: Fill in test.todo() with actual tests from PRD/PES"
